baseURL = '/'
languageCode = 'en-us'
title = 'FINI Domain Trust'
theme = 'ananke'

[[params.ananke_socials]]
name = "github"
url = "https://github.com/fini-net"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/flamingo-internet-navigators/"

[[params.ananke_socials]]
name = "youtube"
url = "https://www.youtube.com/@ChristopherHicksFINI"
